apiVersion: v1
kind: ConfigMap
metadata:
  name: otlp-histogram-config
  namespace: otlp-histogram
data:
  DT_ENDPOINT: "https://<cluster>/e/<env-id>/api/v2/otlp"
  INSECURE_SSL: "false"
  INTERVAL: "60"
